import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
// import { Navbar } from "@/components/navbar";
import { Providers } from "@/providers";
import { cn } from "@/lib/utils";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "deSync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(geistMono.variable, "antialiased")}>
        <Providers>
          
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
