// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	readonly ADMIN_PRIVATE_KEY: `0x${string}`;
	readonly SCROLL_SEPOLIA_RPC_URL: string;
}
