import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "@/components/navbar";
import { Providers } from "@/providers";
import { cn } from "@/lib/utils";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "deSync",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    geistSans.variable,
                    geistMono.variable,
                    "antialiased"
                )}
            >
                <Providers>
                    <div className="font-[family-name:var(--font-geist-mono)] flex flex-col items-center">
                        <Navbar />
                        <main className="container py-10">{children}</main>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
